cc_library(
    name = "EmServicesImpl",
    srcs = [
        "ZEmService.cpp",
    ],
    hdrs = [
        "ZEmService.h",
    ],
    visibility = ["//src/cpp:__subpackages__"],
    deps = [
        "//src/cpp/em:Em",
        "//src/cpp/utils:Trace",
        "//src/interface:cc_interfaces",
    ],
)
