cc_library(
    name = "Probe",
    srcs = ["z_probe.cpp"],
    hdrs = [
    ],
    visibility = ["//:__subpackages__"],
    deps = ["//src/cpp/utils:ServiceUtils"],
)

filegroup(
    name = "z_probe",
    srcs = [
        "z_probe.cpp",
    ],
    visibility = ["//:__subpackages__"],
)
