cc_library(
    name = "ScrumServicesImpl",
    srcs = [
        "ZScrumService.cpp",
    ],
    hdrs = [
        "ZScrumService.h",
    ],
    visibility = ["//src/cpp:__subpackages__"],
    deps = [
        "//src/cpp/utils:Trace",
        "//src/interface:cc_interfaces",
    ],
)
