cc_library(
    name = "ServicesFactory",
    srcs = ["ServiceFactory.cpp"],
    hdrs = [
        "IServiceFactory.h",
        "ZEmServiceFactory.h",
        "ZScrumServiceFactory.h",
    ],
    visibility = ["//src/cpp:__subpackages__"],
    deps = ["//src/cpp/service_implementation:ServicesImpl"],
)
