py_library(
    name = "service_client",
    srcs = [
        "z_service_channel.py",
        "z_service_controller.py",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "//src/interface:py_interfaces",
        "//src/python/package_helper",
    ],  # TODO: minimun dependency?
)
